// Pretty much everything on this file is just makeshift code duct-taped from Gemini. Should be functional to some extent, but need to be properly implemented later by the dev.
use std::env;
//use crate::platform::os::Handle;
use std::path::PathBuf;
use druid::{Selector, commands::CLOSE_WINDOW};
use druid::Data;
use super::CallbackFn;

pub const SYMBOL_ALT: &str = "Alt";
pub const SYMBOL_CTRL: &str = "Ctrl";
pub const SYMBOL_SHIFT: &str = "Shift";
pub const SYMBOL_SUPER: &str = "Win";

pub type Handle = isize;
pub fn get_home_dir() -> Option<PathBuf> {
    env::var("USERPROFILE").ok().map(PathBuf::from)
        .or_else(|| env::var("HOMEDRIVE").ok().and_then(|home_drive| {
            env::var("HOMEPATH").ok().map(|home_path| {
                PathBuf::from(format!("{}{}", home_drive, home_path))
            })
        }))
}

pub fn send_string(_handle: Handle, string: &str) -> Result<(), ()> {
    println!("DEBUG: [Windows] Sending string: {}", string);
    // Real Windows automation code (SendInput) would go here later
    Ok(())
}

pub fn send_backspace(_handle: Handle, count: usize) -> Result<(), ()> {
    println!("DEBUG: [Windows] Sending {} backspaces", count);
    // Real Windows automation code would go here later
    Ok(())
}

pub fn run_event_listener(_callback: &crate::platform::CallbackFn) {
    println!("DEBUG: Key listener started (stub)");
    // Prevent the thread from exiting or crashing
    loop {
        std::thread::sleep(std::time::Duration::from_secs(60));
    }
}
pub fn ensure_accessibility_permission() -> bool {
    true
}

pub fn is_in_text_selection() -> bool {
    false
}

pub fn update_launch_on_login(is_enable: bool) -> Result<(), ()> {
    Ok(()) // Just return success for now
}

pub fn is_launch_on_login() -> bool {
    false // Default to false
}

#[derive(Clone, Data, PartialEq, Eq)]
pub struct SystemTray;

impl SystemTray {
    pub fn new() -> Self { Self }
    pub fn set_title(&self, _title: &str) {}
    pub fn set_menu_item_title(&self, _key: SystemTrayMenuItemKey, _title: &str) {}
    pub fn set_menu_item_callback(&self, _key: SystemTrayMenuItemKey, _callback: impl Fn() + 'static) {}
}

#[derive(Clone, Data, PartialEq, Eq)]
pub enum SystemTrayMenuItemKey {
    Enable,
    ShowUI,
    TypingMethodTelex,
    TypingMethodVNI,
    TypingMethodTelexVNI,
    Exit,
}
// All of these are makeshift and only used for testing. Generated by Gemini.
pub fn get_active_app_name() -> String {
    "GoxKey".to_string()
}

pub fn add_app_change_callback(_callback: Box<dyn Fn() + Send + 'static>) {
    println!("DEBUG: add_app_change_callback called (stub)");
    // In the future, this will use a Win32 WinEventHook
}

pub fn defer_open_app_file_picker(_callback: Box<dyn Fn(Option<String>) + Send + 'static>) {
    // Do nothing. The picker simply won't open, and the app won't crash.
    println!("DEBUG: open_app_file_picker triggered (stub)");
}

pub fn defer_open_text_file_picker(_callback: Box<dyn Fn(Option<String>) + Send + 'static>) {
    println!("DEBUG: open_text_file_picker triggered (stub)");
}

pub fn defer_save_text_file_picker(_callback: Box<dyn Fn(Option<String>) + Send + 'static>) {
    println!("DEBUG: save_text_file_picker triggered (stub)");
}